service: data-store
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    SENSOR_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    WEATHER_TABLE: ${self:service}-${opt:stage, self:provider.stage}-weather
    DARK_SKY: ${file(./config/config.json):DARKSKY_API_KEY}

  iamRoleStatements:
    - Effect: Allow
      Action:
        # - dynamodb:Query
        # - dynamodb:Scan
        # - dynamodb:GetItem
        - dynamodb:PutItem
        # - dynamodb:UpdateItem
        # - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.SENSOR_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.WEATHER_TABLE}"

functions:
  create:
    handler: src/create.create

  weather:
    handler: src/weather.weather
    events:
      - schedule: rate(10 minutes)

resources:
  Resources:
    SensorDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: plant_name
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: plant_name
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.SENSOR_TABLE}

    WeatherDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: location
            AttributeType: S
          - AttributeName: time
            AttributeType: N
        KeySchema:
          - AttributeName: location
            KeyType: HASH
          - AttributeName: time
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.WEATHER_TABLE}